# Generated by Django 3.2 on 2022-05-28 11:25
import bcrypt
from django.db import migrations


def create_admin_user(apps, schema_editor):
    user = apps.get_model('main', 'User')
    user.objects.create(
        first_name='Pedro', last_name='Mendes', email='windowsxpedro@gmail.com',
        phone_number='48999990095', type='admin', password=bcrypt.hashpw('password123', bcrypt.gensalt())
    )


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_admin_user,
            reverse_code=lambda apps, schema_editor: print('reverting create admin user data migration...'))
    ]
