# Generated by Django 3.2 on 2022-06-24 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lesson_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='lesson',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='main.lesson'),
        ),
    ]
