# Generated by Django 3.2 on 2022-06-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220624_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenainformation',
            name='closing_hour',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='arenainformation',
            name='opening_hour',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
